name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build and Test
      run: |
        cd backend/
        chmod +x ./gradlew
        ./gradlew build jacocoTestReport
      working-directory: ${{ github.workspace }}

    - name: Archive Build Reports
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: backend/build/reports/

    - name: Publish Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: backend-artifacts
        path: backend/build/libs/