logging:
  level:
    org.springframework: WARN
---
spring:
  profiles:
    active: dev
---
spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    #ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    username: postgres
    password: 2767981
  cloud:
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: gruppe1cc:europe-west10:cloudappdb

  config:
    activate:
      on-profile: dev
---
spring:
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
  config:
    activate:
      on-profile: test
---
spring:
  mail:
    host: fakehost
    port: 587
    username: fake
    password: fake
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
